import { spawnSync } from 'node:child_process';
import { X509Certificate } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

/**
 * The key pair the dev server listens with, in the shape Vite's `server.https` wants.
 */
export interface DevCertificate {
    cert: string;
    key: string;
}

/**
 * Where the .NET SPA templates keep their exported development certificates. Reusing that
 * folder rather than a folder inside the repository keeps the key out of the working tree,
 * so there is nothing to add to `.gitignore` and nothing to leak in a commit.
 */
function certificateFolder(): string {
    const appData = process.env.APPDATA;

    return appData
        ? path.join(appData, 'ASP.NET', 'https')
        : path.join(process.env.HOME ?? '.', '.aspnet', 'https');
}

/**
 * True when the exported certificate is missing, unreadable or no longer valid.
 *
 * The ASP.NET development certificate is valid for a year. When it is regenerated the export
 * on disk keeps working right up until it expires, at which point the browser would start
 * refusing the dev server for a reason that has nothing to do with the application. Checking
 * the dates here turns that into a silent re-export instead.
 */
function needsExport(certFile: string, keyFile: string): boolean {
    if (!fs.existsSync(certFile) || !fs.existsSync(keyFile)) {
        return true;
    }

    try {
        const certificate = new X509Certificate(fs.readFileSync(certFile));
        const now = Date.now();

        return now < Date.parse(certificate.validFrom) || now > Date.parse(certificate.validTo);
    } catch {
        return true;
    }
}

/**
 * Resolves the certificate the dev server listens with, exporting it from the ASP.NET
 * development certificate store on first run.
 *
 * The API already runs on that certificate (`https://localhost:7003`), and
 * `dotnet dev-certs https --trust` has put it in the machine's trusted root store. Listening
 * on the same certificate is what makes `https://localhost:5173` load without a browser
 * warning; a self-signed certificate generated by a Vite plugin would be untrusted and would
 * interrupt every first request of a session.
 *
 * Returns `null` when the certificate cannot be produced, which leaves the caller to fall
 * back to HTTP rather than making `npm run dev` unusable on a machine without the .NET SDK.
 */
export function resolveDevCertificate(name = 'shophub'): DevCertificate | null {
    const folder = certificateFolder();
    const certFile = path.join(folder, `${name}.pem`);
    const keyFile = path.join(folder, `${name}.key`);

    if (needsExport(certFile, keyFile)) {
        fs.mkdirSync(folder, { recursive: true });

        const exported = spawnSync(
            'dotnet',
            [
                'dev-certs',
                'https',
                '--export-path',
                certFile,
                '--format',
                'Pem',
                '--no-password',
            ],
            { stdio: 'inherit' },
        );

        if (exported.status !== 0) {
            console.warn(
                '[https] Could not export the ASP.NET development certificate. Run ' +
                    '`dotnet dev-certs https --trust` and start the dev server again. ' +
                    'Serving over HTTP for now.',
            );

            return null;
        }
    }

    return {
        cert: fs.readFileSync(certFile, 'utf8'),
        key: fs.readFileSync(keyFile, 'utf8'),
    };
}
