import { api } from '../../shared/api/httpClient';
import type { Cart } from '../../shared/api/types';

export interface CartLineInput {
  productId: string;
  quantity: number;
}

/** Re-prices an anonymous cart. Persists nothing (spec §8.4 state 1). */
export const priceAnonymousCart = (items: CartLineInput[], signal?: AbortSignal) =>
  api.post<Cart>('/api/v1/carts/price', { items }, { signal });

export const fetchServerCart = (signal?: AbortSignal) => api.get<Cart>('/api/v1/carts/me', { signal });

export const addServerCartItem = (input: CartLineInput) => api.post<Cart>('/api/v1/carts/me/items', input);

export const setServerCartQuantity = (productId: string, quantity: number) =>
  api.put<Cart>(`/api/v1/carts/me/items/${productId}`, { quantity });

export const removeServerCartItem = (productId: string) =>
  api.delete<Cart>(`/api/v1/carts/me/items/${productId}`);

/**
 * Merges the localStorage cart into the server cart on login (spec §8.4 state 3).
 *
 * The token is generated by the caller and makes the operation idempotent: a retry after a
 * network blip must not double quantities.
 */
export const mergeCart = (mergeToken: string, items: CartLineInput[]) =>
  api.post<Cart>('/api/v1/carts/merge', { mergeToken, items });
